#!/bin/bash

# Setup ROS distro and ROS
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
apt-get update
apt-get install -y ros-$ROS_DISTRO-ros-base
apt-get install -y ros-$ROS_DISTRO-robot-state-publisher ros-$ROS_DISTRO-joint-state-publisher ros-$ROS_DISTRO-xacro 
apt-get install -y ros-$ROS_DISTRO-robot-localization ros-$ROS_DISTRO-joy ros-$ROS_DISTRO-teleop-twist-joy
apt-get install -y ros-$ROS_DISTRO-nav2-map-server ros-$ROS_DISTRO-nav2-amcl ros-$ROS_DISTRO-navigation2 ros-$ROS_DISTRO-nav2-bringup
apt-get install -y ros-$ROS_DISTRO-v4l2-camera ros-$ROS_DISTRO-image-transport-plugins ros-$ROS_DISTRO-image-tools ros-$ROS_DISTRO-image-common

apt-get install -y build-essential python3-colcon-common-extensions

# Install some misc packages
apt-get install -y cpufrequtils libraspberrypi-bin rt-tests cpuset stress stress-ng

apt-get install -y terminator git

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all
(cd /tmp && ([[ -d sexy-bash-prompt ]] || git clone --depth 1 --config core.autocrlf=false https://github.com/twolfson/sexy-bash-prompt) && cd sexy-bash-prompt && make install)


# clean up to reduce image size
apt-get clean
rm -rf /var/lib/apt/lists/*
