#!/bin/bash

source /opt/ros/humble/setup.bash
source /opt/druk/deployement/local_setup.bash

# export ROS_DOMAIN_ID=75 # DOMAIN ID should be in range [0,101] (included)

ros2 launch ruediger2_bringup ruediger2_online.launch.py