#!/bin/bash

apt-get update

apt-get install -y ros-$ROS_DISTRO-joint-state-publisher ros-$ROS_DISTRO-xacro ros-$ROS_DISTRO-robot-localization ros-$ROS_DISTRO-joy ros-$ROS_DISTRO-teleop-twist-joy
apt-get install -y ros-$ROS_DISTRO-ros2-control ros-$ROS_DISTRO-ros2-controllers
apt-get install -y ros-$ROS_DISTRO-nav2-map-server ros-$ROS_DISTRO-nav2-amcl ros-$ROS_DISTRO-navigation2 ros-$ROS_DISTRO-nav2-bringup
apt-get install -y ros-$ROS_DISTRO-v4l2-camera ros-$ROS_DISTRO-image-transport-plugins ros-$ROS_DISTRO-image-tools ros-$ROS_DISTRO-image-common

apt-get install -y build-essential python3-colcon-common-extensions git

apt-get install -y libwiringpi-dev

# reverse the network names to eth0
# https://askubuntu.com/a/1025201
# ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# clean up to reduce image size
apt-get autoremove -y
apt-get clean
rm -rf /var/lib/apt/lists/*
