#!/bin/bash

# generate a realtime group
addgroup realtime

# update the apt database and install needed packages
apt-get update \
&& apt-get upgrade -y --with-new-pkgs \
&& apt-get install -y \
  network-manager \
  ros-$ROS_DISTRO-joy ros-$ROS_DISTRO-teleop-twist-joy \
  ros-$ROS_DISTRO-teleop-twist-keyboard \
  libwiringpi-dev \
  ament-lint \
  clang-format \
  python3-catkin-pkg \
  python3-colcon-common-extensions \
  python3-pip \
  python3-rosdep2 \
  python3-vcstool \
&& python3 -m pip install colcon-mixin pre-commit

rosdep update \
&& colcon mixin update \
&& colcon metadata update

cd /opt/druk/ros2_ws
. /opt/ros/$ROS_DISTRO/setup.sh \
&& rosdep install -q -y \
  --from-paths src \
  --ignore-src

# install yd-lidar-SDK dependencies
sudo apt install cmake pkg-config
cd /tmp
git clone https://github.com/YDLIDAR/YDLidar-SDK.git /tmp/YDLidar-SDK
mkdir -p /tmp/YDLidar-SDK/build
cd YDLidar-SDK/build
cmake ..
make
make install

# install serial_megapi
cd /tmp
git clone https://github.com/flochre/serial_megapi.git /tmp/serial_megapi
mkdir -p /tmp/serial_megapi/build
cd serial_megapi/build
cmake ..
make
make install

# reverse the network names to eth0 instead of enx<mac-address>
# this is automatique after a apt-get update
# https://askubuntu.com/a/1025201
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# add udev rules to get the megapi and ydlidar on separated tty
echo 'SUBSYSTEM=="tty",ATTRS{idVendor}=="1a86",ATTRS{idProduct}=="7523",SYMLINK+="megapi"' > /etc/udev/rules.d/10-megapi-default.rules
echo 'SUBSYSTEM=="tty",ATTRS{idVendor}=="10c4",ATTRS{idProduct}=="ea60",SYMLINK+="ydlidar"' > /etc/udev/rules.d/10-ydlidar-default.rules

# Activate ip forward for ipv4
sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf

# activate druk service
systemctl daemon-reload
systemctl enable druk.service

# clean up to reduce image size
apt-get autoremove -y && apt-get clean
rm -rf /var/lib/apt/lists/*
rm -rf /opt/druk/ros2_ws
