#!/bin/bash

set -e

# check if connected
# this code ping once the ip
# if the pong does not come in less than 2s
# error is returned
ping -c 1 10.42.33.251 2>&1

mkdir -p /tmp/time_ntp_logger

echo "Time before sync" > /tmp/time_ntp_logger/log.txt
date >> /tmp/time_ntp_logger/log.txt

# Synchronize rpi time with computer
sudo chronyc -a makestep

echo "Time after sync" >> /tmp/time_ntp_logger/log.txt
date >> /tmp/time_ntp_logger/log.txt