name: Build image
on: push

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      check-changes: ${{ steps.filter.outputs.check-changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          check-changes:
            - 'image_builder/**'
            - 'scripts/**'
            - 'Makefile'
            - 'ros-rt-img'
            - '.github/workflows/build.sh'
            - '.github/workflows/setup-dependencies.sh'
            - '.github/workflows/build.yml'

  build-jammy:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.check-changes == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup build dependencies
        run: .github/workflows/setup-dependencies.sh

      - name: Build image
        run: .github/workflows/build.sh jammy-rt-ros2

      - uses: actions/upload-artifact@v3
        with:
          name: img-file-jammy
          path: out/*.img.xz

  # TODO: release image
